---
services:
  backend:
    image: node:23-bullseye
    hostname: motivation-quotes-backend
    container_name: motivation-quotes-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    restart: always

  frontend:
    image: node:23-bullseye
    hostname: motivation-quotes-frontend
    container_name: motivation-quotes-frontend
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app/app
    command: sh -c "npm install && npm run start"
    restart: always
...
