name: Build Docker Image on Release

on:
  release:
    types:
      - published

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-backend:${{ github.event.release.tag_name }} ./backend

      - name: Run docker image
        run: docker run -d --name motivation-quotes-backend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-backend:${{ github.event.release.tag_name }}

      - name: Verify if docker image can run
        run: |
          status=$(curl -o /dev/null -s -w '%{http_code}' http://localhost:3000/languages)
          if [ "$status" -eq 200 ]; then
            echo "Server is up."
          else
            echo "Server is still down, try again."
            exit 1
          fi

      - name: Stop and delete container
        run: docker rm -f motivation-quotes-backend

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-backend:${{ github.event.release.tag_name }}

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-frontend:${{ github.event.release.tag_name }} ./frontend

      - name: Run docker image
        run: docker run -d --name motivation-quotes-frontend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-frontend:${{ github.sha }}

      - name: Verify if docker image can run
        run: |
          status=$(curl -o /dev/null -s -w '%{http_code}' http://localhost:8080)
          if [ "$status" -eq 200 ]; then
            echo "Server is up."
          else
            echo "Server is still down, try again."
            exit 1
          fi

      - name: Stop and delete container
        run: docker rm -f motivation-quotes-frontend

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/motivation-quotes-frontend:${{ github.event.release.tag_name }}
